@startuml Services Class Diagram

class ServiceCategory {
  id: Uuid
  name: String
}

class ServiceProvider {
  id: Uuid
  name: String
  ownerId: Uuid
  location: Location
}

class Service {
  id: Uuid
  name: String
  description: String
  categories: ServiceCategory[]
  provider: ServiceProvider
  picture: Url
  location: Location
  createdAt: DateTime
  updatedAt: DateTime
}
 
Service o--* ServiceCategory : included in
Service <|-- ServiceProvider : provided by

class ServiceSlot {
  id: Uuid
  duration: Int
  service: Service
  startingAt: DateTime
  createdAt: DateTime
  updatedAt: DateTime
}

ServiceSlot <|-- Service : defined by

@enduml
