@startuml MotimActivitiesSequence

actor User
database MotimActivities
database MotimPoints
database MotimUsers

User -> MotimActivities : Send raw activity data
MotimActivities -> MotimUsers : Authorize user
MotimUsers -> MotimActivities : 200 Authorized
MotimActivities -> MotimActivities : Save raw data
User <- MotimActivities : 201 Created
MotimActivities -> MotimPoints : Ping that user has new pointsa
MotimPoints -> MotimUsers : Authorize user
MotimUsers -> MotimPoints : 200 Authorized
MotimPoints -> MotimActivities: Ask for actvity data
MotimActivities -> MotimPoints: 200 Return activity data
MotimPoints -> MotimPoints: Recalculate user points
MotimPoints -> User: 200 Send new points

@enduml

@startuml MotimActivities Entities

entity "Activities" as e01 {
  * id : uuid <<generated>>
  --
  * user_id : uuid
  * value : number
  * created_at : data
  * created_at : data 
  * registered_from : date
  * registered_to : date
  * source : text <<Source>>
  * type : text <<Type>>
}

enum Source {
  GOOGLE_FIT
  HEALTH_KIT
  GARMIN
}

enum Type {
  STEPS
  DISTANCE
}

@enduml