@startmindmap Marketing

* Marketing
** InBound Marketing
*** Hubspot
** Social Media 
*** Facebook Page
*** Kodesmil Page
 
@endmindmap

@startmindmap Products

* Products
** KodeSmil
** Ytt
** Motim
 
@endmindmap

@startmindmap Technology

* Technology
** Vision
*** Have fun with technology
*** Technology == hobby
*** Code less, more life 
*** Plan well and reuse 
*** Work in a way you like 
*** No force, no pushing
** Software
*** Backend
**** Flask (at early stage)
**** Go / GoMicro
**** gRPC
*** Frontend
**** Vue
**** BitDev
**** Monorepo
**** Atomic Design
*** Design
**** Adobe XD
**** Design System Management
*** Mobile
**** Flutter
**** Fastlane
 
@endmindmap
