@startuml Ytt Use Cases

left to right direction
skinparam packageStyle rectangle

actor Customer
actor YttProvider

rectangle System {
  Customer -- (Order Ytt)
  (Order Ytt) .> (Payment) : include
  (Help) .> (Order Ytt) : extends
  (Order Ytt) -- YttProvider
}
@enduml