@startuml Ytt Chat Classes Diagram

class ChatRoom {
  id: Uuid
  createdAt: DateTime
  updatedAt: DateTime
}

class ChatRoomParticipant {
  id: Uuid
  user: User
  role: Roles
  createdAt: DateTime
  updatedAt: DateTime
}

class ChatRoomMessage {
  id: Uuid
  author: ChatRoomParticipant
  createdAt: DateTime
  updatedAt: DateTime
  text: String
}

@enduml