@startuml MF Activity Sequence

actor User
database MotimActivity
database MotimPoints
database MotimUsers

User -> MotimActivity : Send raw activity data
MotimActivity -> MotimUsers : Authorize user
MotimUsers -> MotimActivity : 200 Authorized
MotimActivity -> MotimActivity : Save raw data
User <- MotimActivity : 201 Created
MotimActivity -> MotimPoints : Ping that user has new pointsa
MotimPoints -> MotimUsers : Authorize user
MotimUsers -> MotimPoints : 200 Authorized
MotimPoints -> MotimActivity: Ask for actvity data
MotimActivity -> MotimPoints: 200 Return activity data
MotimPoints -> MotimPoints: Recalculate user points
MotimPoints -> User: 200 Send new points

@enduml

@startuml MF Activity Entities

entity "Activities" as e01 {
  * id : uuid <<generated>>
  --
  * user_id : uuid
  * value : number
  * created_at : data
  * created_at : data 
  * registered_from : date
  * registered_to : date
  * source : text <<Source>>
  * type : text <<Type>>
}

enum Source {
  GOOGLE_FIT
  HEALTH_KIT
  GARMIN
}

enum Type {
  STEPS
  DISTANCE
}

@enduml