@startuml UseCases

left to right direction
skinparam packageStyle rectangle

actor Customer
actor YttProvider

rectangle System {
  Customer -- (Order Ytt)
  (Order Ytt) .> (Payment) : include
  (Help) .> (Order Ytt) : extends
  (Order Ytt) -- YttProvider
}

@enduml

@startuml Classes

class ServiceBooking {
  id: Uuid
  customerId: Uuid
  serviceSlotId: Uuid
  createdAt: DateTime
  updatedAt: DateTime
  confirmedAt: DateTime
}

class ServiceBookingReview {
  id: Uuid
  text: String
  rate: Int
  booking: ServiceBooking
  createdAt: DateTime
  updatedAt: DateTime
}

ServiceBooking <|-- ServiceBookingReview
 
@enduml